# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # Python
  app:
    environment: &environment
      - STAGE=local
    image: cookiecutter-golang-graphql-app-dev
    build:
      args:
        stage: dev

  check:
    image: cookiecutter-golang-graphql-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
